moving_vel_scale : 1
moving_acc_scale : 1

force_threshold: 3
move_group_name: "manipulator"
grinding_eef_link: "pestle_tip"
gathering_eef_link: "spatula_tip"
scooping_eef_link: "spoon_tip"

start_joint_angles:
  - 0.4929
  - -1.2819
  - 1.9723
  - -2.2612
  - 4.7124
  - 2.0637

mortar_hight_calib_joint_angles:
  - 0.4893
  - -1.2454
  - 1.9894
  - -2.3147
  - 4.7124
  - 2.06

mortar_position_calib_joint_angles:
  - 0.4536
  - -1.1243
  - 1.8477
  - -2.2726
  - 4.7094
  - 2.0208


grinding_ready_joint_angles:
  - 0.4929
  - -1.192
  - 2.0145
  - -2.3892
  - 4.7116
  - 2.0635

gathering_ready_joint_angles:
  - 0.4313 
  - -0.9001 
  - 1.4551 
  - -0.5548 
  - 5.1191
  - 1.5696

scooping_ready_joint_angles:
  - 0.4315
  - -0.9353
  - 1.4301 
  - -0.4946
  - 5.1191
  - -1.546
