
move_group_name: "arm"

table_position  :  {x: 0, y: 0, z: -0.04} # 0.015 is hight of UR5e base plate
table_scale  :  {x: 0.5, y: 0.5, z: 0.01}

mortar_position  :  {x:  0.17677, y: 0.17677, z: -0.025}
mortar_inner_scale:  {x:  0.04, y: 0.04, z: 0.036} # official infomation says 0.04 * 0.04 * 0.032 but z is more deep actually 
mortar_hight: 0.045 # mortar top hight from bottom