experiment_time : 90

# end effector params
grinding_ee_link: "pestle_tip"
gathering_ee_link: "spatula_tip"
scooping_ee_link: "spoon_tip"

# ik and motion planner params 
joint_trajectory_controller_name: "scaled_pos_joint_traj_controller"
urdf_name: "ur5e" # support "ur3e" and "ur5e"
ik_solver: "trac_ik" # only "trac_ik" is supported, "ikfast" will be supported in the future
motion_planner_id: "RRTConnect" # recommended "TRRT"(highly optimal but long planning time) or "RRTConnect" (low optimal but fast planning)
planning_time : 20 # timeout for motion planning
max_attempts : 1000

# grinding params
grinding_pos_beginning : 
  - -8
  - 0
grinding_pos_end :
  - -8
  - 0.0001
grinding_center_pos:
  - 0
  - 0
grinding_number_of_rotation : 5
grinding_sec_per_rotation : 0.5 # 0.5 >
grinding_angle_scale : 0.3 #0 - 0.3
grinding_rz_beginning : 35
grinding_rz_end : 35
grinding_vel_scale : 1
grinding_acc_scale : 1
grinding_number_of_waypoints_per_circle : 100
grinding_yaw_bias : rad(pi)
grinding_joint_difference_limit_for_motion_planning : 0.03

# circular gathering params 
gathering_pos_beginning : 
  - 30
  - 0
gathering_pos_end :
  - -22
  - 0.0001
gathering_number_of_rotation : 5
gathering_sec_per_rotation : 2
gathering_angle_scale : 0
gathering_rz_beginning : 35
gathering_rz_end : 35
gathering_vel_scale : 0.1
gathering_acc_scale : 0.1
gathering_number_of_waypoints_per_circle : 50
gathering_yaw_bias :  rad(pi)
gathering_joint_difference_limit_for_motion_planning : 0.1

epicycloid_radius_mm: 8
epicycloid_ratio_R_r: 0.58823529411 # 50 / 85 を計算した値
epicycloid_ratio_d_r: 2 # 170 / 85 を計算した値
epicycloid_waypoints_step_mm: 0.5
epicycloid_angle_scale: 0.3
epicycloid_yaw_bias: 0
epicycloid_grinding_vel_mm_per_sec: 50
epicycloid_yaw_twist_vel_rad_per_sec: 0 # 0.5
epicycloid_grinding_joint_difference_limit_for_motion_planning: 0.1