version: "3.8"

################################################################################

services:
  onolab-ros:
    hostname: onolab_ros
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    image: onolab_ros_noetic
    environment:
      # Pass host user information.
      - HOST_USER=${USER}
      - HOST_UID=1000
      - HOST_GID=1000
      # Display X Server GUI.
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # Map ROS workspace folders.
      - ../:/home/ubuntu/onolab/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Grant access to usb ports
      - /dev/:/dev/
    network_mode: "host"
    extra_hosts:
      - "onolab:127.0.0.1" # Seems that this might be needed for ROS networking
      - "onolab:192.168.56.5" # The host PC
      - "ur5e_ono:192.168.56.42" # UR5e
      - "cobotta:192.168.56.11" # cobotta
      - "sound_sensor:192.168.56.100" #
    expose:
      - "50000" # sound sensor
      - "50001" # send commnad to UR
      - "50002" # external control of UR
      - "50003" # recerve commnad from UR
      - "50004" # script_command_port of UR
      - "5007" # cobotta
    tty: true
