
grinding_eef_link: "pestle_tip"

# grinding params
grinding_pos_begining : 
  - -10
  - 0
grinding_pos_end :
  - -10
  - 0.0001
grinding_center_pos:
  - 0
  - 0
grinding_number_of_rotation : 5
grinding_angle_param : 0.3
grinding_rz_begining : 34
grinding_rz_end : 34
grinding_vel_scale : 1
grinding_acc_scale : 1
grinding_number_of_waypoints_per_circle : 10
grinding_yaw_angle : rad(pi)
