
moveit_group_name: "manipulator"

table_position  :  {x: 0, y: 0, z: -0.015} # 0.015 is hight of UR5e base plate
table_scale  :  {x: 0.9, y: 1.5, z: 0.1}


mortar_position  :  {x:  0.383811929673225, y: 0.3656711454455553, z: 0} # z > 0
mortar_inner_scale:  {x:  0.04, y: 0.04, z: 0.035} # official infomation says 0.04 * 0.04 * 0.032 but z is more deep actually 
mortar_hight: 0.038  # mortar bottom hight from robot base,this value is calibraited by hand (calibrated same hight between pestle tip and mortar top surface)


# test funnel
funnel_position  :  {x:  0.06693, y: 0.323, z: 0}
funnel_scale  :  {x:  0.015, y: 0.015, z: 0.15}

# Master Sizer 3000E
MasterSizer_position  :  {x:  0.073414, y: -0.5184, z: 0}
MasterSizer_scale  :  {x:  0.1, y: 0.1, z: 0.3}
MasterSizer_relay_position  :  {x:  0.073414, y: -0.5184, z: 0}