experiment_time : 90

# end effector params
grinding_ee_link: "pestle_tip"
gathering_ee_link: "spatula_tip"

# ik and motion planner params
robot_urdf_pkg: "grinding_descriptions"
robot_urdf_file_name: "cobotta"
joint_trajectory_controller_name: "arm_controller"
ns: "cobotta"
ik_solver: "trac_ik" # only "trac_ik" is supported, "ikfast" will be supported in the future
motion_planner_id: "TRRT" # recommended "TRRT"(highly optimal but long planning time) or "RRTConnect" (low optimal but fast planning)
planning_time : 20 # planning time to timeout in MoveIt motion planning 

# grinding params
grinding_pos_begining : 
  - -8
  - 0
grinding_pos_end :
  - -8
  - 0.0001
grinding_center_pos:
  - 0
  - 0
grinding_number_of_rotation : 5
grinding_sec_per_rotation : 5 
grinding_angle_scale : 0.3 #0 - 0.3
grinding_rz_begining : 36 
grinding_rz_end : 36
grinding_vel_scale : 1
grinding_acc_scale : 1
grinding_number_of_waypoints_per_circle : 50
grinding_yaw_bias : rad(-pi/2)
grinding_joint_difference_limit_for_motion_planning : 0.03
grinding_max_attempts : 1000

# circular gathering params 
gathering_pos_begining : 
  - -30
  - 0
gathering_pos_end :
  - -23
  - 0.0001
gathering_number_of_rotation : 5
gathering_sec_per_rotation : 5
gathering_angle_scale : 0
gathering_rz_begining : 36
gathering_rz_end : 36
gathering_vel_scale : 0.1
gathering_acc_scale : 0.1
gathering_number_of_waypoints_per_circle : 20
gathering_yaw_bias :  0
gathering_joint_difference_limit_for_motion_planning : 0.03
gathering_max_attempts : 1000
