experimental_time : 90

# end effector params
grinding_eef_link: "pestle_tip"
gathering_eef_link: "spatula_tip"

# ik and motion planner params
urdf_name: "cobotta" # support "ur3e" and "ur5e"
ik_solver: "trac_ik" # only "trac_ik" is supported, "ikfast" will be supported in the future
motion_planner_id: "TRRT" # recommended "TRRT"(highly optimal but long planning time) or "RRTConnect" (low optimal but fast planning)
planning_time : 20 # timeout for motion planning

# grinding params
grinding_pos_beginning : 
  - -10
  - 0
grinding_pos_end :
  - -10
  - 0.0001
grinding_center_pos:
  - 0
  - 0
grinding_number_of_rotation : 10
grinding_angle_param : 0.5
grinding_rz_beginning : 34
grinding_rz_end : 34
grinding_vel_scale : 1
grinding_acc_scale : 1
grinding_number_of_waypoints_per_circle : 10
grinding_yaw_bias : rad(pi)

# circular gathering params 
gathering_pos_beginning : 
  - -35
  - 0
gathering_pos_end :
  - -30 
  - 0.0001
gathering_number_of_rotation : 5
gathering_angle_param : 0
gathering_rz_beginning : 37
gathering_rz_end : 37
gathering_vel_scale : 0.1
gathering_acc_scale : 0.1
gathering_number_of_waypoints_per_circle : 20
gathering_yaw_bias : 0
