cartesian_compliance_controller:

   stiffness: # w.r.t. compliance_ref_link
      trans_x: 500
      trans_y: 500
      trans_z: 500
      rot_x: 20
      rot_y: 20
      rot_z: 20
     
   solver:
      error_scale: 0.1
      iterations: 1
   
   pd_gains:
      trans_x: {p: 0.05}
      trans_y: {p: 0.05}
      trans_z: {p: 0.05}
      rot_x: {p: 0.01}
      rot_y: {p: 0.01}
      rot_z: {p: 0.01}

