robot_base_palte_tickness: 0.015 # [m]
force_threshold: 3 # [N]
Z_calibration_step: 0.001 # [m]

XY_calibration_step: 0.0001 # [m]
calibration_average_force_threshold: 0.1 # [N^2]
calibration_variance_force_threshold: 1 # [N^2]



caliblate_log_dir_path: "/home/ubuntu/onolab/catkin_ws/src/grinding_motion_routines/config/UR5e_grinding_room_903/"

# grinding params
grinding_eef_link: "pestle_tip"
grinding_pos_begining : 
  - -8
  - 0
grinding_pos_end :
  - -8
  - 0.0001
grinding_center_pos:
  - 0
  - 0
grinding_number_of_rotation : 5
grinding_angle_param : 0.3
grinding_rz_begining : 36
grinding_rz_end : 36
grinding_vel_scale : 1
grinding_acc_scale : 1
grinding_number_of_waypoints_per_circle : 10
grinding_yaw_angle : rad(pi)
